CREATE DATABASE logistica;
USE logistica;
CREATE TABLE usuarios(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100));
CREATE TABLE veiculos(id INT AUTO_INCREMENT PRIMARY KEY,placa VARCHAR(10));
CREATE TABLE rastreamento(id INT AUTO_INCREMENT PRIMARY KEY,veiculo_id INT,latitude DECIMAL(10,7),longitude DECIMAL(10,7));
